export type SeedItem = {
  title: string
  area: string
  type: string
  metadata?: Record<string, unknown>
  isFavorite?: boolean
}

// ══════════ TABELA PERIÓDICA — 118 elementos ══════════

export const PERIODIC_TABLE: SeedItem[] = [
  { title:"Hydrogen",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"H",  n:1,   period:1, group:1,  mass:1.008,   cat:"nonmetal",        pt:"Hidrogênio"  } },
  { title:"Helium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"He", n:2,   period:1, group:18, mass:4.003,   cat:"noble gas",       pt:"Hélio"       } },
  { title:"Lithium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Li", n:3,   period:2, group:1,  mass:6.941,   cat:"alkali metal",    pt:"Lítio"       } },
  { title:"Beryllium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Be", n:4,   period:2, group:2,  mass:9.012,   cat:"alkaline earth",  pt:"Berílio"     } },
  { title:"Boron",          area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"B",  n:5,   period:2, group:13, mass:10.811,  cat:"metalloid",       pt:"Boro"        } },
  { title:"Carbon",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"C",  n:6,   period:2, group:14, mass:12.011,  cat:"nonmetal",        pt:"Carbono"     }, isFavorite:true },
  { title:"Nitrogen",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"N",  n:7,   period:2, group:15, mass:14.007,  cat:"nonmetal",        pt:"Nitrogênio"  } },
  { title:"Oxygen",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"O",  n:8,   period:2, group:16, mass:15.999,  cat:"nonmetal",        pt:"Oxigênio"    }, isFavorite:true },
  { title:"Fluorine",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"F",  n:9,   period:2, group:17, mass:18.998,  cat:"halogen",         pt:"Flúor"       } },
  { title:"Neon",           area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ne", n:10,  period:2, group:18, mass:20.180,  cat:"noble gas",       pt:"Neônio"      } },
  { title:"Sodium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Na", n:11,  period:3, group:1,  mass:22.990,  cat:"alkali metal",    pt:"Sódio"       } },
  { title:"Magnesium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Mg", n:12,  period:3, group:2,  mass:24.305,  cat:"alkaline earth",  pt:"Magnésio"    } },
  { title:"Aluminium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Al", n:13,  period:3, group:13, mass:26.982,  cat:"post-transition", pt:"Alumínio"    } },
  { title:"Silicon",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Si", n:14,  period:3, group:14, mass:28.086,  cat:"metalloid",       pt:"Silício"     } },
  { title:"Phosphorus",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"P",  n:15,  period:3, group:15, mass:30.974,  cat:"nonmetal",        pt:"Fósforo"     } },
  { title:"Sulfur",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"S",  n:16,  period:3, group:16, mass:32.065,  cat:"nonmetal",        pt:"Enxofre"     } },
  { title:"Chlorine",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cl", n:17,  period:3, group:17, mass:35.453,  cat:"halogen",         pt:"Cloro"       } },
  { title:"Argon",          area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ar", n:18,  period:3, group:18, mass:39.948,  cat:"noble gas",       pt:"Argônio"     } },
  { title:"Potassium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"K",  n:19,  period:4, group:1,  mass:39.098,  cat:"alkali metal",    pt:"Potássio"    } },
  { title:"Calcium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ca", n:20,  period:4, group:2,  mass:40.078,  cat:"alkaline earth",  pt:"Cálcio"      } },
  { title:"Scandium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Sc", n:21,  period:4, group:3,  mass:44.956,  cat:"transition",      pt:"Escândio"    } },
  { title:"Titanium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ti", n:22,  period:4, group:4,  mass:47.867,  cat:"transition",      pt:"Titânio"     } },
  { title:"Vanadium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"V",  n:23,  period:4, group:5,  mass:50.942,  cat:"transition",      pt:"Vanádio"     } },
  { title:"Chromium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cr", n:24,  period:4, group:6,  mass:51.996,  cat:"transition",      pt:"Cromo"       } },
  { title:"Manganese",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Mn", n:25,  period:4, group:7,  mass:54.938,  cat:"transition",      pt:"Manganês"    } },
  { title:"Iron",           area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Fe", n:26,  period:4, group:8,  mass:55.845,  cat:"transition",      pt:"Ferro"       }, isFavorite:true },
  { title:"Cobalt",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Co", n:27,  period:4, group:9,  mass:58.933,  cat:"transition",      pt:"Cobalto"     } },
  { title:"Nickel",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ni", n:28,  period:4, group:10, mass:58.693,  cat:"transition",      pt:"Níquel"      } },
  { title:"Copper",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cu", n:29,  period:4, group:11, mass:63.546,  cat:"transition",      pt:"Cobre"       }, isFavorite:true },
  { title:"Zinc",           area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Zn", n:30,  period:4, group:12, mass:65.38,   cat:"transition",      pt:"Zinco"       } },
  { title:"Gallium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ga", n:31,  period:4, group:13, mass:69.723,  cat:"post-transition", pt:"Gálio"       } },
  { title:"Germanium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ge", n:32,  period:4, group:14, mass:72.63,   cat:"metalloid",       pt:"Germânio"    } },
  { title:"Arsenic",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"As", n:33,  period:4, group:15, mass:74.922,  cat:"metalloid",       pt:"Arsênio"     } },
  { title:"Selenium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Se", n:34,  period:4, group:16, mass:78.96,   cat:"nonmetal",        pt:"Selênio"     } },
  { title:"Bromine",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Br", n:35,  period:4, group:17, mass:79.904,  cat:"halogen",         pt:"Bromo"       } },
  { title:"Krypton",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Kr", n:36,  period:4, group:18, mass:83.798,  cat:"noble gas",       pt:"Criptônio"   } },
  { title:"Rubidium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Rb", n:37,  period:5, group:1,  mass:85.468,  cat:"alkali metal",    pt:"Rubídio"     } },
  { title:"Strontium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Sr", n:38,  period:5, group:2,  mass:87.62,   cat:"alkaline earth",  pt:"Estrôncio"   } },
  { title:"Yttrium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Y",  n:39,  period:5, group:3,  mass:88.906,  cat:"transition",      pt:"Ítrio"       } },
  { title:"Zirconium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Zr", n:40,  period:5, group:4,  mass:91.224,  cat:"transition",      pt:"Zircônio"    } },
  { title:"Niobium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Nb", n:41,  period:5, group:5,  mass:92.906,  cat:"transition",      pt:"Nióbio"      } },
  { title:"Molybdenum",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Mo", n:42,  period:5, group:6,  mass:95.96,   cat:"transition",      pt:"Molibdênio"  } },
  { title:"Technetium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Tc", n:43,  period:5, group:7,  mass:98,      cat:"transition",      pt:"Tecnécio"    } },
  { title:"Ruthenium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ru", n:44,  period:5, group:8,  mass:101.07,  cat:"transition",      pt:"Rutênio"     } },
  { title:"Rhodium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Rh", n:45,  period:5, group:9,  mass:102.906, cat:"transition",      pt:"Ródio"       } },
  { title:"Palladium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pd", n:46,  period:5, group:10, mass:106.42,  cat:"transition",      pt:"Paládio"     } },
  { title:"Silver",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ag", n:47,  period:5, group:11, mass:107.868, cat:"transition",      pt:"Prata"       }, isFavorite:true },
  { title:"Cadmium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cd", n:48,  period:5, group:12, mass:112.411, cat:"transition",      pt:"Cádmio"      } },
  { title:"Indium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"In", n:49,  period:5, group:13, mass:114.818, cat:"post-transition", pt:"Índio"       } },
  { title:"Tin",            area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Sn", n:50,  period:5, group:14, mass:118.71,  cat:"post-transition", pt:"Estanho"     } },
  { title:"Antimony",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Sb", n:51,  period:5, group:15, mass:121.76,  cat:"metalloid",       pt:"Antimônio"   } },
  { title:"Tellurium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Te", n:52,  period:5, group:16, mass:127.60,  cat:"metalloid",       pt:"Telúrio"     } },
  { title:"Iodine",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"I",  n:53,  period:5, group:17, mass:126.904, cat:"halogen",         pt:"Iodo"        } },
  { title:"Xenon",          area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Xe", n:54,  period:5, group:18, mass:131.293, cat:"noble gas",       pt:"Xenônio"     } },
  { title:"Caesium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cs", n:55,  period:6, group:1,  mass:132.905, cat:"alkali metal",    pt:"Césio"       } },
  { title:"Barium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ba", n:56,  period:6, group:2,  mass:137.327, cat:"alkaline earth",  pt:"Bário"       } },
  { title:"Lanthanum",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"La", n:57,  period:6, group:3,  mass:138.905, cat:"lanthanide",      pt:"Lantânio"    } },
  { title:"Cerium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ce", n:58,  period:6, group:0,  mass:140.116, cat:"lanthanide",      pt:"Cério"       } },
  { title:"Praseodymium",   area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pr", n:59,  period:6, group:0,  mass:140.908, cat:"lanthanide",      pt:"Praseodímio" } },
  { title:"Neodymium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Nd", n:60,  period:6, group:0,  mass:144.242, cat:"lanthanide",      pt:"Neodímio"    } },
  { title:"Promethium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pm", n:61,  period:6, group:0,  mass:145,     cat:"lanthanide",      pt:"Promécio"    } },
  { title:"Samarium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Sm", n:62,  period:6, group:0,  mass:150.36,  cat:"lanthanide",      pt:"Samário"     } },
  { title:"Europium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Eu", n:63,  period:6, group:0,  mass:151.964, cat:"lanthanide",      pt:"Európio"     } },
  { title:"Gadolinium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Gd", n:64,  period:6, group:0,  mass:157.25,  cat:"lanthanide",      pt:"Gadolínio"   } },
  { title:"Terbium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Tb", n:65,  period:6, group:0,  mass:158.925, cat:"lanthanide",      pt:"Térbio"      } },
  { title:"Dysprosium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Dy", n:66,  period:6, group:0,  mass:162.500, cat:"lanthanide",      pt:"Disprósio"   } },
  { title:"Holmium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ho", n:67,  period:6, group:0,  mass:164.930, cat:"lanthanide",      pt:"Hólmio"      } },
  { title:"Erbium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Er", n:68,  period:6, group:0,  mass:167.259, cat:"lanthanide",      pt:"Érbio"       } },
  { title:"Thulium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Tm", n:69,  period:6, group:0,  mass:168.934, cat:"lanthanide",      pt:"Túlio"       } },
  { title:"Ytterbium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Yb", n:70,  period:6, group:0,  mass:173.04,  cat:"lanthanide",      pt:"Itérbio"     } },
  { title:"Lutetium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Lu", n:71,  period:6, group:3,  mass:174.967, cat:"lanthanide",      pt:"Lutécio"     } },
  { title:"Hafnium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Hf", n:72,  period:6, group:4,  mass:178.49,  cat:"transition",      pt:"Háfnio"      } },
  { title:"Tantalum",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ta", n:73,  period:6, group:5,  mass:180.948, cat:"transition",      pt:"Tântalo"     } },
  { title:"Tungsten",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"W",  n:74,  period:6, group:6,  mass:183.84,  cat:"transition",      pt:"Tungstênio"  } },
  { title:"Rhenium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Re", n:75,  period:6, group:7,  mass:186.207, cat:"transition",      pt:"Rênio"       } },
  { title:"Osmium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Os", n:76,  period:6, group:8,  mass:190.23,  cat:"transition",      pt:"Ósmio"       } },
  { title:"Iridium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ir", n:77,  period:6, group:9,  mass:192.217, cat:"transition",      pt:"Irídio"      } },
  { title:"Platinum",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pt", n:78,  period:6, group:10, mass:195.084, cat:"transition",      pt:"Platina"     }, isFavorite:true },
  { title:"Gold",           area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Au", n:79,  period:6, group:11, mass:196.967, cat:"transition",      pt:"Ouro"        }, isFavorite:true },
  { title:"Mercury (element)", area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Hg", n:80, period:6, group:12, mass:200.59, cat:"transition",    pt:"Mercúrio"    } },
  { title:"Thallium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Tl", n:81,  period:6, group:13, mass:204.383, cat:"post-transition", pt:"Tálio"       } },
  { title:"Lead",           area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pb", n:82,  period:6, group:14, mass:207.2,   cat:"post-transition", pt:"Chumbo"      } },
  { title:"Bismuth",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Bi", n:83,  period:6, group:15, mass:208.980, cat:"post-transition", pt:"Bismuto"     } },
  { title:"Polonium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Po", n:84,  period:6, group:16, mass:209,     cat:"post-transition", pt:"Polônio"     } },
  { title:"Astatine",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"At", n:85,  period:6, group:17, mass:210,     cat:"halogen",         pt:"Ástato"      } },
  { title:"Radon",          area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Rn", n:86,  period:6, group:18, mass:222,     cat:"noble gas",       pt:"Radônio"     } },
  { title:"Francium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Fr", n:87,  period:7, group:1,  mass:223,     cat:"alkali metal",    pt:"Frâncio"     } },
  { title:"Radium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ra", n:88,  period:7, group:2,  mass:226,     cat:"alkaline earth",  pt:"Rádio"       } },
  { title:"Actinium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ac", n:89,  period:7, group:3,  mass:227,     cat:"actinide",        pt:"Actínio"     } },
  { title:"Thorium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Th", n:90,  period:7, group:0,  mass:232.038, cat:"actinide",        pt:"Tório"       } },
  { title:"Protactinium",   area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pa", n:91,  period:7, group:0,  mass:231.036, cat:"actinide",        pt:"Protactínio" } },
  { title:"Uranium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"U",  n:92,  period:7, group:0,  mass:238.029, cat:"actinide",        pt:"Urânio"      }, isFavorite:true },
  { title:"Neptunium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Np", n:93,  period:7, group:0,  mass:237,     cat:"actinide",        pt:"Netúnio"     } },
  { title:"Plutonium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Pu", n:94,  period:7, group:0,  mass:244,     cat:"actinide",        pt:"Plutônio"    } },
  { title:"Americium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Am", n:95,  period:7, group:0,  mass:243,     cat:"actinide",        pt:"Amerício"    } },
  { title:"Curium",         area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cm", n:96,  period:7, group:0,  mass:247,     cat:"actinide",        pt:"Cúrio"       } },
  { title:"Berkelium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Bk", n:97,  period:7, group:0,  mass:247,     cat:"actinide",        pt:"Berquélio"   } },
  { title:"Californium",    area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cf", n:98,  period:7, group:0,  mass:251,     cat:"actinide",        pt:"Califórnio"  } },
  { title:"Einsteinium",    area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Es", n:99,  period:7, group:0,  mass:252,     cat:"actinide",        pt:"Einstênio"   } },
  { title:"Fermium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Fm", n:100, period:7, group:0,  mass:257,     cat:"actinide",        pt:"Férmio"      } },
  { title:"Mendelevium",    area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Md", n:101, period:7, group:0,  mass:258,     cat:"actinide",        pt:"Mendelévio"  } },
  { title:"Nobelium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"No", n:102, period:7, group:0,  mass:259,     cat:"actinide",        pt:"Nobélio"     } },
  { title:"Lawrencium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Lr", n:103, period:7, group:3,  mass:262,     cat:"actinide",        pt:"Laurêncio"   } },
  { title:"Rutherfordium",  area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Rf", n:104, period:7, group:4,  mass:265,     cat:"transition",      pt:"Rutherfórdio"} },
  { title:"Dubnium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Db", n:105, period:7, group:5,  mass:268,     cat:"transition",      pt:"Dúbnio"      } },
  { title:"Seaborgium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Sg", n:106, period:7, group:6,  mass:271,     cat:"transition",      pt:"Seabórgio"   } },
  { title:"Bohrium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Bh", n:107, period:7, group:7,  mass:270,     cat:"transition",      pt:"Bório"       } },
  { title:"Hassium",        area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Hs", n:108, period:7, group:8,  mass:277,     cat:"transition",      pt:"Hássio"      } },
  { title:"Meitnerium",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Mt", n:109, period:7, group:9,  mass:276,     cat:"unknown",         pt:"Meitnério"   } },
  { title:"Darmstadtium",   area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ds", n:110, period:7, group:10, mass:281,     cat:"unknown",         pt:"Darmstácio"  } },
  { title:"Roentgenium",    area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Rg", n:111, period:7, group:11, mass:280,     cat:"unknown",         pt:"Roentgênio"  } },
  { title:"Copernicium",    area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Cn", n:112, period:7, group:12, mass:285,     cat:"transition",      pt:"Copernício"  } },
  { title:"Nihonium",       area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Nh", n:113, period:7, group:13, mass:284,     cat:"unknown",         pt:"Nihônio"     } },
  { title:"Flerovium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Fl", n:114, period:7, group:14, mass:289,     cat:"post-transition", pt:"Fleróvio"    } },
  { title:"Moscovium",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Mc", n:115, period:7, group:15, mass:288,     cat:"unknown",         pt:"Moscóvio"    } },
  { title:"Livermorium",    area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Lv", n:116, period:7, group:16, mass:293,     cat:"unknown",         pt:"Livermório"  } },
  { title:"Tennessine",     area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Ts", n:117, period:7, group:17, mass:294,     cat:"unknown",         pt:"Tennessínio" } },
  { title:"Oganesson",      area:"ELEMENTOS", type:"ELEMENT", metadata:{ symbol:"Og", n:118, period:7, group:18, mass:294,     cat:"unknown",         pt:"Oganessônio" } },
]

// ══════════ COSMOS ══════════

export const COSMOS_ITEMS: SeedItem[] = [
  { title:"Solar System",              area:"COSMOS", type:"CONCEPT", isFavorite:true },
  { title:"Mercury (planet)",          area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:1 } },
  { title:"Venus",                     area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:2 } },
  { title:"Earth",                     area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:3 }, isFavorite:true },
  { title:"Mars",                      area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:4 }, isFavorite:true },
  { title:"Jupiter",                   area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:5 } },
  { title:"Saturn",                    area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:6 } },
  { title:"Uranus",                    area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:7 } },
  { title:"Neptune",                   area:"COSMOS", type:"OBJECT",  metadata:{ category:"planet", order:8 } },
  { title:"Pluto",                     area:"COSMOS", type:"OBJECT",  metadata:{ category:"dwarf planet" } },
  { title:"Sun",                       area:"COSMOS", type:"OBJECT",  metadata:{ category:"star" }, isFavorite:true },
  { title:"Sirius",                    area:"COSMOS", type:"OBJECT",  metadata:{ category:"star" } },
  { title:"Alpha Centauri",            area:"COSMOS", type:"OBJECT",  metadata:{ category:"star system" } },
  { title:"Betelgeuse",                area:"COSMOS", type:"OBJECT",  metadata:{ category:"supergiant" } },
  { title:"Milky Way",                 area:"COSMOS", type:"CONCEPT", isFavorite:true },
  { title:"Andromeda Galaxy",          area:"COSMOS", type:"OBJECT",  metadata:{ category:"galaxy" } },
  { title:"Pillars of Creation",       area:"COSMOS", type:"OBJECT",  metadata:{ category:"nebula" }, isFavorite:true },
  { title:"Orion Nebula",              area:"COSMOS", type:"OBJECT",  metadata:{ category:"nebula" } },
  { title:"Crab Nebula",               area:"COSMOS", type:"OBJECT",  metadata:{ category:"nebula" } },
  { title:"Helix Nebula",              area:"COSMOS", type:"OBJECT",  metadata:{ category:"planetary nebula" } },
  { title:"Orion (constellation)",     area:"COSMOS", type:"CONCEPT", metadata:{ category:"constellation" } },
  { title:"Southern Cross",            area:"COSMOS", type:"CONCEPT", metadata:{ category:"constellation" } },
  { title:"Ursa Major",                area:"COSMOS", type:"CONCEPT", metadata:{ category:"constellation" } },
  { title:"Black hole",                area:"COSMOS", type:"CONCEPT" },
  { title:"Big Bang",                  area:"COSMOS", type:"CONCEPT", isFavorite:true },
  { title:"Dark matter",               area:"COSMOS", type:"CONCEPT" },
  { title:"Hubble Space Telescope",    area:"COSMOS", type:"OBJECT" },
  { title:"James Webb Space Telescope",area:"COSMOS", type:"OBJECT" },
  { title:"International Space Station",area:"COSMOS",type:"OBJECT" },
]

// ══════════ PESSOAS — Compositores ══════════

export const COMPOSERS: SeedItem[] = [
  { title:"Johann Sebastian Bach",      area:"MUSICOS", type:"PERSON", metadata:{ born:1685, died:1750, nat:"German"    }, isFavorite:true },
  { title:"Ludwig van Beethoven",       area:"MUSICOS", type:"PERSON", metadata:{ born:1770, died:1827, nat:"German"    }, isFavorite:true },
  { title:"Wolfgang Amadeus Mozart",    area:"MUSICOS", type:"PERSON", metadata:{ born:1756, died:1791, nat:"Austrian"  }, isFavorite:true },
  { title:"Franz Schubert",             area:"MUSICOS", type:"PERSON", metadata:{ born:1797, died:1828, nat:"Austrian"  } },
  { title:"Johannes Brahms",            area:"MUSICOS", type:"PERSON", metadata:{ born:1833, died:1897, nat:"German"    } },
  { title:"Frédéric Chopin",            area:"MUSICOS", type:"PERSON", metadata:{ born:1810, died:1849, nat:"Polish"    }, isFavorite:true },
  { title:"Robert Schumann",            area:"MUSICOS", type:"PERSON", metadata:{ born:1810, died:1856, nat:"German"    } },
  { title:"Franz Liszt",                area:"MUSICOS", type:"PERSON", metadata:{ born:1811, died:1886, nat:"Hungarian" } },
  { title:"Richard Wagner",             area:"MUSICOS", type:"PERSON", metadata:{ born:1813, died:1883, nat:"German"    } },
  { title:"Giuseppe Verdi",             area:"MUSICOS", type:"PERSON", metadata:{ born:1813, died:1901, nat:"Italian"   } },
  { title:"Pyotr Ilyich Tchaikovsky",   area:"MUSICOS", type:"PERSON", metadata:{ born:1840, died:1893, nat:"Russian"   }, isFavorite:true },
  { title:"Antonín Dvořák",             area:"MUSICOS", type:"PERSON", metadata:{ born:1841, died:1904, nat:"Czech"     } },
  { title:"Edvard Grieg",               area:"MUSICOS", type:"PERSON", metadata:{ born:1843, died:1907, nat:"Norwegian" } },
  { title:"Nikolai Rimsky-Korsakov",    area:"MUSICOS", type:"PERSON", metadata:{ born:1844, died:1908, nat:"Russian"   } },
  { title:"Gustav Mahler",              area:"MUSICOS", type:"PERSON", metadata:{ born:1860, died:1911, nat:"Austrian"  } },
  { title:"Claude Debussy",             area:"MUSICOS", type:"PERSON", metadata:{ born:1862, died:1918, nat:"French"    }, isFavorite:true },
  { title:"Richard Strauss",            area:"MUSICOS", type:"PERSON", metadata:{ born:1864, died:1949, nat:"German"    } },
  { title:"Jean Sibelius",              area:"MUSICOS", type:"PERSON", metadata:{ born:1865, died:1957, nat:"Finnish"   } },
  { title:"Sergei Rachmaninoff",        area:"MUSICOS", type:"PERSON", metadata:{ born:1873, died:1943, nat:"Russian"   } },
  { title:"Maurice Ravel",              area:"MUSICOS", type:"PERSON", metadata:{ born:1875, died:1937, nat:"French"    } },
  { title:"Béla Bartók",                area:"MUSICOS", type:"PERSON", metadata:{ born:1881, died:1945, nat:"Hungarian" } },
  { title:"Igor Stravinsky",            area:"MUSICOS", type:"PERSON", metadata:{ born:1882, died:1971, nat:"Russian"   }, isFavorite:true },
  { title:"Sergei Prokofiev",           area:"MUSICOS", type:"PERSON", metadata:{ born:1891, died:1953, nat:"Russian"   } },
  { title:"Dmitri Shostakovich",        area:"MUSICOS", type:"PERSON", metadata:{ born:1906, died:1975, nat:"Russian"   } },
  { title:"Leonard Bernstein",          area:"MUSICOS", type:"PERSON", metadata:{ born:1918, died:1990, nat:"American"  } },
  { title:"Heitor Villa-Lobos",         area:"MUSICOS", type:"PERSON", metadata:{ born:1887, died:1959, nat:"Brazilian" }, isFavorite:true },
  { title:"Antonio Vivaldi",            area:"MUSICOS", type:"PERSON", metadata:{ born:1678, died:1741, nat:"Italian"   } },
  { title:"George Frideric Handel",     area:"MUSICOS", type:"PERSON", metadata:{ born:1685, died:1759, nat:"German"    } },
  { title:"Joseph Haydn",               area:"MUSICOS", type:"PERSON", metadata:{ born:1732, died:1809, nat:"Austrian"  } },
  { title:"Claudio Monteverdi",         area:"MUSICOS", type:"PERSON", metadata:{ born:1567, died:1643, nat:"Italian"   } },
  { title:"Giacomo Puccini",            area:"MUSICOS", type:"PERSON", metadata:{ born:1858, died:1924, nat:"Italian"   } },
  { title:"Camille Saint-Saëns",        area:"MUSICOS", type:"PERSON", metadata:{ born:1835, died:1921, nat:"French"    } },
  { title:"Erik Satie",                 area:"MUSICOS", type:"PERSON", metadata:{ born:1866, died:1925, nat:"French"    } },
  { title:"Astor Piazzolla",            area:"MUSICOS", type:"PERSON", metadata:{ born:1921, died:1992, nat:"Argentine" } },
  { title:"Philip Glass",               area:"MUSICOS", type:"PERSON", metadata:{ born:1937, nat:"American"            } },
  { title:"Arvo Pärt",                  area:"MUSICOS", type:"PERSON", metadata:{ born:1935, nat:"Estonian"            } },
  { title:"Johann Pachelbel",           area:"MUSICOS", type:"PERSON", metadata:{ born:1653, died:1706, nat:"German"   } },
  { title:"Pietro Locatelli",           area:"MUSICOS", type:"PERSON", metadata:{ born:1695, died:1764, nat:"Italian"  } },
]

// ══════════ PESSOAS — Cientistas ══════════

export const SCIENTISTS: SeedItem[] = [
  { title:"Isaac Newton",               area:"CIENTISTAS", type:"PERSON", metadata:{ born:1643, died:1727, nat:"English",  field:"Física, matemática"  }, isFavorite:true },
  { title:"Albert Einstein",            area:"CIENTISTAS", type:"PERSON", metadata:{ born:1879, died:1955, nat:"German",   field:"Física teórica"       }, isFavorite:true },
  { title:"Charles Darwin",             area:"CIENTISTAS", type:"PERSON", metadata:{ born:1809, died:1882, nat:"English",  field:"Biologia"             }, isFavorite:true },
  { title:"Galileo Galilei",            area:"CIENTISTAS", type:"PERSON", metadata:{ born:1564, died:1642, nat:"Italian",  field:"Física, astronomia"   } },
  { title:"Nikola Tesla",               area:"CIENTISTAS", type:"PERSON", metadata:{ born:1856, died:1943, nat:"Serbian",  field:"Engenharia elétrica"  } },
  { title:"Marie Curie",                area:"CIENTISTAS", type:"PERSON", metadata:{ born:1867, died:1934, nat:"Polish",   field:"Física, química"      }, isFavorite:true },
  { title:"Stephen Hawking",            area:"CIENTISTAS", type:"PERSON", metadata:{ born:1942, died:2018, nat:"English",  field:"Cosmologia"           } },
  { title:"Richard Feynman",            area:"CIENTISTAS", type:"PERSON", metadata:{ born:1918, died:1988, nat:"American", field:"Física quântica"      } },
  { title:"Niels Bohr",                 area:"CIENTISTAS", type:"PERSON", metadata:{ born:1885, died:1962, nat:"Danish",   field:"Física quântica"      } },
  { title:"Max Planck",                 area:"CIENTISTAS", type:"PERSON", metadata:{ born:1858, died:1947, nat:"German",   field:"Física quântica"      } },
  { title:"Michael Faraday",            area:"CIENTISTAS", type:"PERSON", metadata:{ born:1791, died:1867, nat:"English",  field:"Eletromagnetismo"     } },
  { title:"James Clerk Maxwell",        area:"CIENTISTAS", type:"PERSON", metadata:{ born:1831, died:1879, nat:"Scottish", field:"Eletromagnetismo"     } },
  { title:"Nicolaus Copernicus",        area:"CIENTISTAS", type:"PERSON", metadata:{ born:1473, died:1543, nat:"Polish",   field:"Astronomia"           } },
  { title:"Johannes Kepler",            area:"CIENTISTAS", type:"PERSON", metadata:{ born:1571, died:1630, nat:"German",   field:"Astronomia"           } },
  { title:"Louis Pasteur",              area:"CIENTISTAS", type:"PERSON", metadata:{ born:1822, died:1895, nat:"French",   field:"Microbiologia"        } },
  { title:"Gregor Mendel",              area:"CIENTISTAS", type:"PERSON", metadata:{ born:1822, died:1884, nat:"Austrian", field:"Genética"             } },
  { title:"Alan Turing",                area:"CIENTISTAS", type:"PERSON", metadata:{ born:1912, died:1954, nat:"British",  field:"Computação"           }, isFavorite:true },
  { title:"Carl Sagan",                 area:"CIENTISTAS", type:"PERSON", metadata:{ born:1934, died:1996, nat:"American", field:"Astronomia"           } },
  { title:"Archimedes",                 area:"CIENTISTAS", type:"PERSON", metadata:{ born:-287, died:-212, nat:"Greek",    field:"Matemática, física"   } },
  { title:"Carl Friedrich Gauss",       area:"CIENTISTAS", type:"PERSON", metadata:{ born:1777, died:1855, nat:"German",   field:"Matemática"           } },
  { title:"Leonhard Euler",             area:"CIENTISTAS", type:"PERSON", metadata:{ born:1707, died:1783, nat:"Swiss",    field:"Matemática"           } },
  { title:"Dmitri Mendeleev",           area:"CIENTISTAS", type:"PERSON", metadata:{ born:1834, died:1907, nat:"Russian",  field:"Química"              } },
  { title:"Antoine Lavoisier",          area:"CIENTISTAS", type:"PERSON", metadata:{ born:1743, died:1794, nat:"French",   field:"Química"              } },
  { title:"Ada Lovelace",               area:"CIENTISTAS", type:"PERSON", metadata:{ born:1815, died:1852, nat:"English",  field:"Computação"           } },
]

// ══════════ PESSOAS — Filósofos ══════════

export const PHILOSOPHERS: SeedItem[] = [
  { title:"Socrates",                   area:"FILOSOFOS", type:"PERSON", metadata:{ born:-470, died:-399, nat:"Greek",    field:"Ética"                }, isFavorite:true },
  { title:"Plato",                      area:"FILOSOFOS", type:"PERSON", metadata:{ born:-428, died:-348, nat:"Greek",    field:"Metafísica"           }, isFavorite:true },
  { title:"Aristotle",                  area:"FILOSOFOS", type:"PERSON", metadata:{ born:-384, died:-322, nat:"Greek",    field:"Lógica, ciência"      }, isFavorite:true },
  { title:"Immanuel Kant",              area:"FILOSOFOS", type:"PERSON", metadata:{ born:1724, died:1804, nat:"German",   field:"Filosofia crítica"    }, isFavorite:true },
  { title:"Friedrich Nietzsche",        area:"FILOSOFOS", type:"PERSON", metadata:{ born:1844, died:1900, nat:"German",   field:"Existencialismo"      } },
  { title:"Georg Wilhelm Friedrich Hegel", area:"FILOSOFOS", type:"PERSON", metadata:{ born:1770, died:1831, nat:"German", field:"Dialética"          } },
  { title:"Baruch Spinoza",             area:"FILOSOFOS", type:"PERSON", metadata:{ born:1632, died:1677, nat:"Dutch",    field:"Panteísmo"            } },
  { title:"John Locke",                 area:"FILOSOFOS", type:"PERSON", metadata:{ born:1632, died:1704, nat:"English",  field:"Empirismo"            } },
  { title:"David Hume",                 area:"FILOSOFOS", type:"PERSON", metadata:{ born:1711, died:1776, nat:"Scottish", field:"Ceticismo"            } },
  { title:"Jean-Paul Sartre",           area:"FILOSOFOS", type:"PERSON", metadata:{ born:1905, died:1980, nat:"French",   field:"Existencialismo"      } },
  { title:"Simone de Beauvoir",         area:"FILOSOFOS", type:"PERSON", metadata:{ born:1908, died:1986, nat:"French",   field:"Feminismo, existencial"} },
  { title:"Michel Foucault",            area:"FILOSOFOS", type:"PERSON", metadata:{ born:1926, died:1984, nat:"French",   field:"Pós-estruturalismo"   } },
  { title:"Ludwig Wittgenstein",        area:"FILOSOFOS", type:"PERSON", metadata:{ born:1889, died:1951, nat:"Austrian", field:"Linguagem, lógica"    } },
  { title:"Karl Marx",                  area:"FILOSOFOS", type:"PERSON", metadata:{ born:1818, died:1883, nat:"German",   field:"Marxismo"             } },
  { title:"Confucius",                  area:"FILOSOFOS", type:"PERSON", metadata:{ born:-551, died:-479, nat:"Chinese",  field:"Ética, governo"       } },
  { title:"Lao Tzu",                    area:"FILOSOFOS", type:"PERSON", metadata:{ born:-601, nat:"Chinese",             field:"Taoísmo"              } },
  { title:"René Descartes",             area:"FILOSOFOS", type:"PERSON", metadata:{ born:1596, died:1650, nat:"French",   field:"Racionalismo"         } },
]

// ══════════ PESSOAS — Pintores ══════════

export const PAINTERS: SeedItem[] = [
  { title:"Leonardo da Vinci",          area:"PINTORES", type:"PERSON", metadata:{ born:1452, died:1519, nat:"Italian"  }, isFavorite:true },
  { title:"Michelangelo",               area:"PINTORES", type:"PERSON", metadata:{ born:1475, died:1564, nat:"Italian"  }, isFavorite:true },
  { title:"Raphael",                    area:"PINTORES", type:"PERSON", metadata:{ born:1483, died:1520, nat:"Italian"  } },
  { title:"Rembrandt",                  area:"PINTORES", type:"PERSON", metadata:{ born:1606, died:1669, nat:"Dutch"    } },
  { title:"Johannes Vermeer",           area:"PINTORES", type:"PERSON", metadata:{ born:1632, died:1675, nat:"Dutch"    } },
  { title:"Diego Velázquez",            area:"PINTORES", type:"PERSON", metadata:{ born:1599, died:1660, nat:"Spanish"  } },
  { title:"Francisco Goya",             area:"PINTORES", type:"PERSON", metadata:{ born:1746, died:1828, nat:"Spanish"  } },
  { title:"Claude Monet",               area:"PINTORES", type:"PERSON", metadata:{ born:1840, died:1926, nat:"French"   }, isFavorite:true },
  { title:"Vincent van Gogh",           area:"PINTORES", type:"PERSON", metadata:{ born:1853, died:1890, nat:"Dutch"    }, isFavorite:true },
  { title:"Pablo Picasso",              area:"PINTORES", type:"PERSON", metadata:{ born:1881, died:1973, nat:"Spanish"  }, isFavorite:true },
  { title:"Salvador Dalí",              area:"PINTORES", type:"PERSON", metadata:{ born:1904, died:1989, nat:"Spanish"  } },
  { title:"Frida Kahlo",                area:"PINTORES", type:"PERSON", metadata:{ born:1907, died:1954, nat:"Mexican"  } },
  { title:"Wassily Kandinsky",          area:"PINTORES", type:"PERSON", metadata:{ born:1866, died:1944, nat:"Russian"  } },
  { title:"Jackson Pollock",            area:"PINTORES", type:"PERSON", metadata:{ born:1912, died:1956, nat:"American" } },
  { title:"Andy Warhol",                area:"PINTORES", type:"PERSON", metadata:{ born:1928, died:1987, nat:"American" } },
  { title:"Caravaggio",                 area:"PINTORES", type:"PERSON", metadata:{ born:1571, died:1610, nat:"Italian"  } },
  { title:"Gustav Klimt",               area:"PINTORES", type:"PERSON", metadata:{ born:1862, died:1918, nat:"Austrian" } },
  { title:"Édouard Manet",              area:"PINTORES", type:"PERSON", metadata:{ born:1832, died:1883, nat:"French"   } },
  { title:"Edgar Degas",                area:"PINTORES", type:"PERSON", metadata:{ born:1834, died:1917, nat:"French"   } },
  { title:"Pierre-Auguste Renoir",      area:"PINTORES", type:"PERSON", metadata:{ born:1841, died:1919, nat:"French"   } },
]

// ══════════ PESSOAS — Escritores ══════════

export const WRITERS: SeedItem[] = [
  { title:"Homer",                      area:"ESCRITORES", type:"PERSON", metadata:{ born:-800, nat:"Greek",      field:"Epopeia"   }, isFavorite:true },
  { title:"Dante Alighieri",            area:"ESCRITORES", type:"PERSON", metadata:{ born:1265, died:1321, nat:"Italian",  field:"Poesia"    }, isFavorite:true },
  { title:"William Shakespeare",        area:"ESCRITORES", type:"PERSON", metadata:{ born:1564, died:1616, nat:"English",  field:"Teatro"    }, isFavorite:true },
  { title:"Miguel de Cervantes",        area:"ESCRITORES", type:"PERSON", metadata:{ born:1547, died:1616, nat:"Spanish",  field:"Romance"   } },
  { title:"Leo Tolstoy",                area:"ESCRITORES", type:"PERSON", metadata:{ born:1828, died:1910, nat:"Russian",  field:"Romance"   } },
  { title:"Fyodor Dostoevsky",          area:"ESCRITORES", type:"PERSON", metadata:{ born:1821, died:1881, nat:"Russian",  field:"Romance"   } },
  { title:"Franz Kafka",                area:"ESCRITORES", type:"PERSON", metadata:{ born:1883, died:1924, nat:"Czech",    field:"Romance"   } },
  { title:"James Joyce",                area:"ESCRITORES", type:"PERSON", metadata:{ born:1882, died:1941, nat:"Irish",    field:"Modernismo"} },
  { title:"Jorge Luis Borges",          area:"ESCRITORES", type:"PERSON", metadata:{ born:1899, died:1986, nat:"Argentine",field:"Conto"     }, isFavorite:true },
  { title:"Gabriel García Márquez",     area:"ESCRITORES", type:"PERSON", metadata:{ born:1927, died:2014, nat:"Colombian",field:"Romance"   }, isFavorite:true },
  { title:"Virginia Woolf",             area:"ESCRITORES", type:"PERSON", metadata:{ born:1882, died:1941, nat:"English",  field:"Romance"   } },
  { title:"Albert Camus",               area:"ESCRITORES", type:"PERSON", metadata:{ born:1913, died:1960, nat:"French",   field:"Absurdo"   } },
  { title:"George Orwell",              area:"ESCRITORES", type:"PERSON", metadata:{ born:1903, died:1950, nat:"English",  field:"Distopia"  } },
  { title:"Victor Hugo",                area:"ESCRITORES", type:"PERSON", metadata:{ born:1802, died:1885, nat:"French",   field:"Romance"   } },
  { title:"Charles Dickens",            area:"ESCRITORES", type:"PERSON", metadata:{ born:1812, died:1870, nat:"English",  field:"Romance"   } },
  { title:"Clarice Lispector",          area:"ESCRITORES", type:"PERSON", metadata:{ born:1920, died:1977, nat:"Brazilian",field:"Romance"   }, isFavorite:true },
  { title:"Machado de Assis",           area:"ESCRITORES", type:"PERSON", metadata:{ born:1839, died:1908, nat:"Brazilian",field:"Romance"   }, isFavorite:true },
  { title:"Fernando Pessoa",            area:"ESCRITORES", type:"PERSON", metadata:{ born:1888, died:1935, nat:"Portuguese",field:"Poesia"   } },
  { title:"José Saramago",              area:"ESCRITORES", type:"PERSON", metadata:{ born:1922, died:2010, nat:"Portuguese",field:"Romance"  } },
  { title:"Johann Wolfgang von Goethe", area:"ESCRITORES", type:"PERSON", metadata:{ born:1749, died:1832, nat:"German",   field:"Poesia"   } },
]

// ══════════ BIBLIOTECA ══════════

export const GREAT_BOOKS: SeedItem[] = [
  { title:"Iliad",                         area:"BIBLIOTECA", type:"READING", metadata:{ author:"Homer",           year:-750, genre:"Epopeia"       }, isFavorite:true },
  { title:"The Odyssey",                   area:"BIBLIOTECA", type:"READING", metadata:{ author:"Homer",           year:-725, genre:"Epopeia"       } },
  { title:"Don Quixote",                   area:"BIBLIOTECA", type:"READING", metadata:{ author:"Cervantes",       year:1605, genre:"Romance"       }, isFavorite:true },
  { title:"War and Peace",                 area:"BIBLIOTECA", type:"READING", metadata:{ author:"Tolstoy",         year:1869, genre:"Romance"       } },
  { title:"Crime and Punishment",          area:"BIBLIOTECA", type:"READING", metadata:{ author:"Dostoevsky",      year:1866, genre:"Romance"       } },
  { title:"The Brothers Karamazov",        area:"BIBLIOTECA", type:"READING", metadata:{ author:"Dostoevsky",      year:1880, genre:"Romance"       } },
  { title:"Ulysses (novel)",               area:"BIBLIOTECA", type:"READING", metadata:{ author:"Joyce",           year:1922, genre:"Modernismo"    } },
  { title:"One Hundred Years of Solitude", area:"BIBLIOTECA", type:"READING", metadata:{ author:"García Márquez",  year:1967, genre:"Realismo mágico"}, isFavorite:true },
  { title:"The Divine Comedy",             area:"BIBLIOTECA", type:"READING", metadata:{ author:"Dante",           year:1320, genre:"Poema épico"   }, isFavorite:true },
  { title:"Hamlet",                        area:"BIBLIOTECA", type:"READING", metadata:{ author:"Shakespeare",     year:1603, genre:"Tragédia"      } },
  { title:"The Republic (Plato)",          area:"BIBLIOTECA", type:"READING", metadata:{ author:"Plato",           year:-380, genre:"Filosofia"     } },
  { title:"Faust (Goethe)",                area:"BIBLIOTECA", type:"READING", metadata:{ author:"Goethe",          year:1808, genre:"Drama"         } },
  { title:"Anna Karenina",                 area:"BIBLIOTECA", type:"READING", metadata:{ author:"Tolstoy",         year:1878, genre:"Romance"       } },
  { title:"Nineteen Eighty-Four",          area:"BIBLIOTECA", type:"READING", metadata:{ author:"Orwell",          year:1949, genre:"Distopia"      } },
  { title:"Brave New World",               area:"BIBLIOTECA", type:"READING", metadata:{ author:"Huxley",          year:1932, genre:"Distopia"      } },
  { title:"The Metamorphosis",             area:"BIBLIOTECA", type:"READING", metadata:{ author:"Kafka",           year:1915, genre:"Novela"        } },
  { title:"Les Misérables",                area:"BIBLIOTECA", type:"READING", metadata:{ author:"Victor Hugo",     year:1862, genre:"Romance"       } },
  { title:"Moby-Dick",                     area:"BIBLIOTECA", type:"READING", metadata:{ author:"Melville",        year:1851, genre:"Romance"       } },
  { title:"The Aeneid",                    area:"BIBLIOTECA", type:"READING", metadata:{ author:"Virgil",          year:-19,  genre:"Epopeia"       } },
]

// ══════════ MÚSICA — Obras ══════════

export const GREAT_COMPOSITIONS: SeedItem[] = [
  { title:"The Well-Tempered Clavier",       area:"MUSICA", type:"WORK", metadata:{ composer:"J.S. Bach",    year:1722 }, isFavorite:true },
  { title:"Symphony No. 9 (Beethoven)",      area:"MUSICA", type:"WORK", metadata:{ composer:"Beethoven",   year:1824 }, isFavorite:true },
  { title:"The Four Seasons (Vivaldi)",      area:"MUSICA", type:"WORK", metadata:{ composer:"Vivaldi",     year:1725 }, isFavorite:true },
  { title:"Messiah (Handel)",                area:"MUSICA", type:"WORK", metadata:{ composer:"Handel",      year:1741 } },
  { title:"Swan Lake",                       area:"MUSICA", type:"WORK", metadata:{ composer:"Tchaikovsky", year:1877 } },
  { title:"The Rite of Spring",              area:"MUSICA", type:"WORK", metadata:{ composer:"Stravinsky",  year:1913 } },
  { title:"Bolero (Ravel)",                  area:"MUSICA", type:"WORK", metadata:{ composer:"Ravel",       year:1928 } },
  { title:"Clair de lune",                   area:"MUSICA", type:"WORK", metadata:{ composer:"Debussy",     year:1905 } },
  { title:"Goldberg Variations",             area:"MUSICA", type:"WORK", metadata:{ composer:"J.S. Bach",   year:1741 } },
  { title:"Piano Sonata No. 14 (Beethoven)", area:"MUSICA", type:"WORK", metadata:{ composer:"Beethoven",   year:1801, nickname:"Moonlight" } },
  { title:"Nocturnes (Chopin)",              area:"MUSICA", type:"WORK", metadata:{ composer:"Chopin",      year:1830 } },
  { title:"The Magic Flute",                 area:"MUSICA", type:"WORK", metadata:{ composer:"Mozart",      year:1791 } },
  { title:"Don Giovanni",                    area:"MUSICA", type:"WORK", metadata:{ composer:"Mozart",      year:1787 } },
]

// ══════════ PINTURAS — Obras ══════════

export const GREAT_PAINTINGS: SeedItem[] = [
  { title:"Mona Lisa",                  area:"PINTURAS", type:"WORK", metadata:{ artist:"Leonardo da Vinci", year:1503 }, isFavorite:true },
  { title:"The Last Supper (Leonardo)", area:"PINTURAS", type:"WORK", metadata:{ artist:"Leonardo da Vinci", year:1498 }, isFavorite:true },
  { title:"The Sistine Chapel ceiling", area:"PINTURAS", type:"WORK", metadata:{ artist:"Michelangelo",      year:1512 } },
  { title:"The School of Athens",       area:"PINTURAS", type:"WORK", metadata:{ artist:"Raphael",           year:1511 } },
  { title:"Girl with a Pearl Earring",  area:"PINTURAS", type:"WORK", metadata:{ artist:"Vermeer",           year:1665 } },
  { title:"The Starry Night",           area:"PINTURAS", type:"WORK", metadata:{ artist:"Van Gogh",          year:1889 }, isFavorite:true },
  { title:"Sunflowers (Van Gogh)",      area:"PINTURAS", type:"WORK", metadata:{ artist:"Van Gogh",          year:1888 } },
  { title:"Guernica",                   area:"PINTURAS", type:"WORK", metadata:{ artist:"Picasso",           year:1937 }, isFavorite:true },
  { title:"The Persistence of Memory", area:"PINTURAS", type:"WORK", metadata:{ artist:"Dalí",              year:1931 } },
  { title:"Water Lilies (Monet)",       area:"PINTURAS", type:"WORK", metadata:{ artist:"Monet",            year:1906 } },
  { title:"Las Meninas",                area:"PINTURAS", type:"WORK", metadata:{ artist:"Velázquez",        year:1656 } },
  { title:"The Birth of Venus (Botticelli)", area:"PINTURAS", type:"WORK", metadata:{ artist:"Botticelli",  year:1485 } },
  { title:"Night Watch",                area:"PINTURAS", type:"WORK", metadata:{ artist:"Rembrandt",        year:1642 } },
  { title:"The Creation of Adam",       area:"PINTURAS", type:"WORK", metadata:{ artist:"Michelangelo",     year:1512 } },
]

// ══════════ CIÊNCIAS — Conceitos, Teorias, Unidades SI ══════════

export const SCIENCE_CONCEPTS: SeedItem[] = [
  { title:"Theory of relativity",        area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  { title:"Quantum mechanics",           area:"CIENCIAS", type:"CONCEPT" },
  { title:"Evolution",                   area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  { title:"Electromagnetism",            area:"CIENCIAS", type:"CONCEPT" },
  { title:"Thermodynamics",              area:"CIENCIAS", type:"CONCEPT" },
  { title:"Newton's laws of motion",     area:"CIENCIAS", type:"CONCEPT" },
  { title:"DNA",                         area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  { title:"Pythagoras theorem",          area:"CIENCIAS", type:"CONCEPT" },
  { title:"Fibonacci number",            area:"CIENCIAS", type:"CONCEPT" },
  { title:"Pi (mathematical constant)",  area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  { title:"Euler's identity",            area:"CIENCIAS", type:"CONCEPT" },
  { title:"Periodic table",              area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  { title:"Standard Model (physics)",    area:"CIENCIAS", type:"CONCEPT" },
  { title:"Higgs boson",                 area:"CIENCIAS", type:"CONCEPT" },
  { title:"Big Bang",                    area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  // Unidades SI
  { title:"International System of Units", area:"CIENCIAS", type:"CONCEPT", isFavorite:true },
  { title:"Metre",           area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"m",   quantity:"length",             cat:"SI unit" } },
  { title:"Kilogram",        area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"kg",  quantity:"mass",               cat:"SI unit" } },
  { title:"Second",          area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"s",   quantity:"time",               cat:"SI unit" } },
  { title:"Ampere",          area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"A",   quantity:"electric current",   cat:"SI unit" } },
  { title:"Kelvin",          area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"K",   quantity:"temperature",        cat:"SI unit" } },
  { title:"Mole (unit)",     area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"mol", quantity:"amount",             cat:"SI unit" } },
  { title:"Candela",         area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"cd",  quantity:"luminous intensity", cat:"SI unit" } },
  // Constantes físicas
  { title:"Speed of light",             area:"CIENCIAS", type:"CONCEPT", metadata:{ value:"299,792,458 m/s", symbol:"c" } },
  { title:"Gravitational constant",     area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"G" } },
  { title:"Planck constant",            area:"CIENCIAS", type:"CONCEPT", metadata:{ symbol:"h" } },
  { title:"Avogadro constant",          area:"CIENCIAS", type:"CONCEPT", metadata:{ value:"6.022×10²³ mol⁻¹", symbol:"Nₐ" } },
]

// ══════════ HISTÓRIA ══════════

export const HISTORY_ITEMS: SeedItem[] = [
  { title:"Ancient Egypt",              area:"HISTORIA", type:"CONCEPT", metadata:{ period:"-3100 a -30"  } },
  { title:"Ancient Greece",             area:"HISTORIA", type:"CONCEPT", metadata:{ period:"-800 a -146"  }, isFavorite:true },
  { title:"Roman Empire",               area:"HISTORIA", type:"CONCEPT", metadata:{ period:"27 a 476"     }, isFavorite:true },
  { title:"Byzantine Empire",           area:"HISTORIA", type:"CONCEPT", metadata:{ period:"330 a 1453"   } },
  { title:"Mesopotamia",                area:"HISTORIA", type:"CONCEPT", metadata:{ period:"-3500 a -539" } },
  { title:"Maya civilization",          area:"HISTORIA", type:"CONCEPT" },
  { title:"Inca Empire",                area:"HISTORIA", type:"CONCEPT" },
  { title:"French Revolution",          area:"HISTORIA", type:"EVENT",   metadata:{ year:1789 }, isFavorite:true },
  { title:"Industrial Revolution",      area:"HISTORIA", type:"EVENT",   metadata:{ period:"1760-1840"    }, isFavorite:true },
  { title:"World War I",                area:"HISTORIA", type:"EVENT",   metadata:{ period:"1914-1918"    } },
  { title:"World War II",               area:"HISTORIA", type:"EVENT",   metadata:{ period:"1939-1945"    } },
  { title:"Renaissance",                area:"HISTORIA", type:"ERA",     metadata:{ period:"1300-1600"    }, isFavorite:true },
  { title:"Enlightenment",              area:"HISTORIA", type:"ERA",     metadata:{ period:"1685-1815"    } },
  { title:"Age of Exploration",         area:"HISTORIA", type:"ERA",     metadata:{ period:"1400-1600"    } },
  { title:"Moon landing",               area:"HISTORIA", type:"EVENT",   metadata:{ year:1969 }, isFavorite:true },
  { title:"Printing press",             area:"HISTORIA", type:"EVENT",   metadata:{ year:1440 } },
  { title:"Fall of Constantinople",     area:"HISTORIA", type:"EVENT",   metadata:{ year:1453 } },
  { title:"Russian Revolution",         area:"HISTORIA", type:"EVENT",   metadata:{ year:1917 } },
]

// ══════════ NATUREZA ══════════

export const NATURE_ITEMS: SeedItem[] = [
  { title:"Amazon rainforest",   area:"NATUREZA", type:"PLACE",   isFavorite:true },
  { title:"Sahara",              area:"NATUREZA", type:"PLACE" },
  { title:"Great Barrier Reef",  area:"NATUREZA", type:"PLACE",   isFavorite:true },
  { title:"Mariana Trench",      area:"NATUREZA", type:"PLACE" },
  { title:"Atlantic Ocean",      area:"NATUREZA", type:"PLACE" },
  { title:"Pacific Ocean",       area:"NATUREZA", type:"PLACE" },
  { title:"Mount Everest",       area:"NATUREZA", type:"PLACE" },
  { title:"Blue whale",          area:"NATUREZA", type:"SPECIES" },
  { title:"Giant sequoia",       area:"NATUREZA", type:"SPECIES" },
  { title:"Snow leopard",        area:"NATUREZA", type:"SPECIES" },
  { title:"Giant panda",         area:"NATUREZA", type:"SPECIES" },
  { title:"African elephant",    area:"NATUREZA", type:"SPECIES" },
  { title:"Northern Lights",     area:"NATUREZA", type:"CONCEPT", isFavorite:true },
  { title:"Photosynthesis",      area:"NATUREZA", type:"CONCEPT" },
  { title:"Plate tectonics",     area:"NATUREZA", type:"CONCEPT" },
]

// ══════════ ARQUITETURA ══════════

export const ARCHITECTURE_ITEMS: SeedItem[] = [
  { title:"Colosseum",           area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Rome",       year:80    }, isFavorite:true },
  { title:"Parthenon",           area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Athens",     year:-432  }, isFavorite:true },
  { title:"Sagrada Família",     area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Barcelona",  year:1882  } },
  { title:"Eiffel Tower",        area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Paris",      year:1889  }, isFavorite:true },
  { title:"Taj Mahal",           area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Agra",       year:1653  }, isFavorite:true },
  { title:"Machu Picchu",        area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Peru",       year:1450  }, isFavorite:true },
  { title:"Great Pyramid of Giza",area:"ARQUITETURA",type:"PLACE", metadata:{ location:"Egypt",      year:-2560 }, isFavorite:true },
  { title:"Hagia Sophia",        area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Istanbul",   year:537   } },
  { title:"Notre-Dame de Paris", area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Paris",      year:1345  } },
  { title:"Angkor Wat",          area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Cambodia",   year:1150  } },
  { title:"Sydney Opera House",  area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Sydney",     year:1973  } },
  { title:"Fallingwater",        area:"ARQUITETURA", type:"PLACE", metadata:{ location:"Pennsylvania",year:1939 } },
  { title:"Stonehenge",          area:"ARQUITETURA", type:"PLACE", metadata:{ location:"England",    year:-3000 } },
]

// ══════════ EXPORTAÇÃO TOTAL ══════════

export const ALL_SEED_ITEMS: SeedItem[] = [
  ...PERIODIC_TABLE,
  ...COSMOS_ITEMS,
  ...COMPOSERS,
  ...SCIENTISTS,
  ...PHILOSOPHERS,
  ...PAINTERS,
  ...WRITERS,
  ...GREAT_BOOKS,
  ...GREAT_COMPOSITIONS,
  ...GREAT_PAINTINGS,
  ...SCIENCE_CONCEPTS,
  ...HISTORY_ITEMS,
  ...NATURE_ITEMS,
  ...ARCHITECTURE_ITEMS,
]
